import { NativeModules } from 'react-native';

NativeModules.StripeTerminalReactNative = {
  getConstants: () => ({
    FETCH_TOKEN_PROVIDER: 'FETCH_TOKEN_PROVIDER',
    CHANGE_CONNECTION_STATUS: 'CHANGE_CONNECTION_STATUS',
    CHANGE_PAYMENT_STATUS: 'CHANGE_PAYMENT_STATUS',
    FINISH_DISCOVERING_READERS: 'FINISH_DISCOVERING_READERS',
    FINISH_INSTALLING_UPDATE: 'FINISH_INSTALLING_UPDATE',
    REQUEST_READER_DISPLAY_MESSAGE: 'REQUEST_READER_DISPLAY_MESSAGE',
    REQUEST_READER_INPUT: 'REQUEST_READER_INPUT',
    REPORT_AVAILABLE_UPDATE: 'REPORT_AVAILABLE_UPDATE',
    REPORT_UNEXPECTED_READER_DISCONNECT: 'REPORT_UNEXPECTED_READER_DISCONNECT',
    REPORT_UPDATE_PROGRESS: 'REPORT_UPDATE_PROGRESS',
    START_INSTALLING_UPDATE: 'START_INSTALLING_UPDATE',
    UPDATE_DISCOVERED_READERS: 'UPDATE_DISCOVERED_READERS',
  }),
};
