/* eslint-env jest */
import { NativeModules } from 'react-native';

NativeModules.StripeTerminalReactNative = {
  getConstants: () => ({
    FETCH_TOKEN_PROVIDER: 'FETCH_TOKEN_PROVIDER',
    CHANGE_CONNECTION_STATUS: 'CHANGE_CONNECTION_STATUS',
    CHANGE_PAYMENT_STATUS: 'CHANGE_PAYMENT_STATUS',
    FINISH_DISCOVERING_READERS: 'FINISH_DISCOVERING_READERS',
    FINISH_INSTALLING_UPDATE: 'FINISH_INSTALLING_UPDATE',
    REQUEST_READER_DISPLAY_MESSAGE: 'REQUEST_READER_DISPLAY_MESSAGE',
    REQUEST_READER_INPUT: 'REQUEST_READER_INPUT',
    REPORT_AVAILABLE_UPDATE: 'REPORT_AVAILABLE_UPDATE',
    REPORT_UNEXPECTED_READER_DISCONNECT: 'REPORT_UNEXPECTED_READER_DISCONNECT',
    REPORT_UPDATE_PROGRESS: 'REPORT_UPDATE_PROGRESS',
    START_INSTALLING_UPDATE: 'START_INSTALLING_UPDATE',
    UPDATE_DISCOVERED_READERS: 'UPDATE_DISCOVERED_READERS',
    START_READER_RECONNECT: 'START_READER_RECONNECT',
    READER_RECONNECT_SUCCEED: 'READER_RECONNECT_SUCCEED',
    READER_RECONNECT_FAIL: 'READER_RECONNECT_FAIL',
    CHANGE_OFFLINE_STATUS: 'CHANGE_OFFLINE_STATUS',
    FORWARD_PAYMENT_INTENT: 'FORWARD_PAYMENT_INTENT',
    REPORT_FORWARDING_ERROR: 'REPORT_FORWARDING_ERROR',
    DISCONNECT: 'DISCONNECT',
    UPDATE_BATTERY_LEVEL: 'UPDATE_BATTERY_LEVEL',
    REPORT_LOW_BATTERY_WARNING: 'REPORT_LOW_BATTERY_WARNING',
    REPORT_READER_EVENT: 'REPORT_READER_EVENT',
    ACCEPT_TERMS_OF_SERVICE: 'ACCEPT_TERMS_OF_SERVICE',
    PAYMENT_METHOD_SELECTION_REQUIRED: 'PAYMENT_METHOD_SELECTION_REQUIRED',
    QR_CODE_DISPLAY_REQUIRED: 'QR_CODE_DISPLAY_REQUIRED',
  }),
  // Add properties needed for NativeEventEmitter
  addListener: jest.fn(),
  removeListeners: jest.fn(),
};
