export const ErrorCode = {
  // Integration-like
  CANCEL_FAILED: 'CANCEL_FAILED',
  NOT_CONNECTED_TO_READER: 'NOT_CONNECTED_TO_READER',
  ALREADY_CONNECTED_TO_READER: 'ALREADY_CONNECTED_TO_READER',
  BLUETOOTH_PERMISSION_DENIED: 'BLUETOOTH_PERMISSION_DENIED',
  CONFIRM_INVALID_PAYMENT_INTENT: 'CONFIRM_INVALID_PAYMENT_INTENT',
  CONFIRM_INVALID_SETUP_INTENT: 'CONFIRM_INVALID_SETUP_INTENT',
  INVALID_CLIENT_SECRET: 'INVALID_CLIENT_SECRET',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',
  UNEXPECTED_OPERATION: 'UNEXPECTED_OPERATION',
  UNSUPPORTED_SDK: 'UNSUPPORTED_SDK',
  USB_PERMISSION_DENIED: 'USB_PERMISSION_DENIED',
  MISSING_PREREQUISITE: 'MISSING_PREREQUISITE',
  MISSING_REQUIRED_PARAMETER: 'MISSING_REQUIRED_PARAMETER',
  INVALID_REQUIRED_PARAMETER: 'INVALID_REQUIRED_PARAMETER',
  INVALID_TIP_PARAMETER: 'INVALID_TIP_PARAMETER',
  INVALID_MOTO_CONFIGURATION: 'INVALID_MOTO_CONFIGURATION',
  TAP_TO_PAY_LIBRARY_NOT_INCLUDED: 'TAP_TO_PAY_LIBRARY_NOT_INCLUDED',
  TAP_TO_PAY_UNSUPPORTED_DEVICE: 'TAP_TO_PAY_UNSUPPORTED_DEVICE',
  TAP_TO_PAY_UNSUPPORTED_ANDROID_VERSION:
    'TAP_TO_PAY_UNSUPPORTED_ANDROID_VERSION',
  TAP_TO_PAY_DEVICE_TAMPERED: 'TAP_TO_PAY_DEVICE_TAMPERED',
  TAP_TO_PAY_INSECURE_ENVIRONMENT: 'TAP_TO_PAY_INSECURE_ENVIRONMENT',
  TAP_TO_PAY_DEBUG_NOT_SUPPORTED: 'TAP_TO_PAY_DEBUG_NOT_SUPPORTED',
  TAP_TO_PAY_UNSUPPORTED_PROCESSOR: 'TAP_TO_PAY_UNSUPPORTED_PROCESSOR',
  OFFLINE_MODE_UNSUPPORTED_ANDROID_VERSION:
    'OFFLINE_MODE_UNSUPPORTED_ANDROID_VERSION',

  // User-like
  CANCELED: 'CANCELED',
  LOCATION_SERVICES_DISABLED: 'LOCATION_SERVICES_DISABLED',
  BLUETOOTH_SCAN_TIMED_OUT: 'BLUETOOTH_SCAN_TIMED_OUT',
  BLUETOOTH_LOW_ENERGY_UNSUPPORTED: 'BLUETOOTH_LOW_ENERGY_UNSUPPORTED',
  READER_SOFTWARE_UPDATE_FAILED_BATTERY_LOW:
    'READER_SOFTWARE_UPDATE_FAILED_BATTERY_LOW',
  READER_SOFTWARE_UPDATE_FAILED_INTERRUPTED:
    'READER_SOFTWARE_UPDATE_FAILED_INTERRUPTED',
  CARD_INSERT_NOT_READ: 'CARD_INSERT_NOT_READ',
  CARD_SWIPE_NOT_READ: 'CARD_SWIPE_NOT_READ',
  CARD_READ_TIMED_OUT: 'CARD_READ_TIMED_OUT',
  CARD_REMOVED: 'CARD_REMOVED',
  CUSTOMER_CONSENT_REQUIRED: 'CUSTOMER_CONSENT_REQUIRED',
  CARD_LEFT_IN_READER: 'CARD_LEFT_IN_READER',
  USB_DISCOVERY_TIMED_OUT: 'USB_DISCOVERY_TIMED_OUT',
  FEATURE_NOT_ENABLED_ON_ACCOUNT: 'FEATURE_NOT_ENABLED_ON_ACCOUNT',

  // Reader / Hardware
  READER_BUSY: 'READER_BUSY',
  READER_COMMUNICATION_ERROR: 'READER_COMMUNICATION_ERROR',
  READER_TAMPERED: 'READER_TAMPERED',
  BLUETOOTH_ERROR: 'BLUETOOTH_ERROR',
  BLUETOOTH_DISCONNECTED: 'BLUETOOTH_DISCONNECTED',
  BLUETOOTH_RECONNECT_STARTED: 'BLUETOOTH_RECONNECT_STARTED',
  USB_DISCONNECTED: 'USB_DISCONNECTED',
  USB_RECONNECT_STARTED: 'USB_RECONNECT_STARTED',
  READER_CONNECTED_TO_ANOTHER_DEVICE: 'READER_CONNECTED_TO_ANOTHER_DEVICE',
  READER_BATTERY_CRITICALLY_LOW: 'READER_BATTERY_CRITICALLY_LOW',
  READER_SOFTWARE_UPDATE_FAILED: 'READER_SOFTWARE_UPDATE_FAILED',
  READER_SOFTWARE_UPDATE_FAILED_READER_ERROR:
    'READER_SOFTWARE_UPDATE_FAILED_READER_ERROR',
  READER_SOFTWARE_UPDATE_FAILED_SERVER_ERROR:
    'READER_SOFTWARE_UPDATE_FAILED_SERVER_ERROR',
  TAP_TO_PAY_NFC_DISABLED: 'TAP_TO_PAY_NFC_DISABLED',
  UNSUPPORTED_READER_VERSION: 'UNSUPPORTED_READER_VERSION',
  GENERIC_READER_ERROR: 'GENERIC_READER_ERROR',

  // Unexpected
  UNEXPECTED_SDK_ERROR: 'UNEXPECTED_SDK_ERROR',

  // Payment
  DECLINED_BY_STRIPE_API: 'DECLINED_BY_STRIPE_API',
  DECLINED_BY_READER: 'DECLINED_BY_READER',

  // Network
  REQUEST_TIMED_OUT: 'REQUEST_TIMED_OUT',
  STRIPE_API_CONNECTION_ERROR: 'STRIPE_API_CONNECTION_ERROR',
  STRIPE_API_ERROR: 'STRIPE_API_ERROR',
  STRIPE_API_RESPONSE_DECODING_ERROR: 'STRIPE_API_RESPONSE_DECODING_ERROR',
  CONNECTION_TOKEN_PROVIDER_ERROR: 'CONNECTION_TOKEN_PROVIDER_ERROR',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  ANDROID_API_LEVEL_ERROR: 'ANDROID_API_LEVEL_ERROR',

  // Offline / Account / Currency constraints
  AMOUNT_EXCEEDS_MAX_OFFLINE_AMOUNT: 'AMOUNT_EXCEEDS_MAX_OFFLINE_AMOUNT',
  OFFLINE_PAYMENTS_DATABASE_TOO_LARGE: 'OFFLINE_PAYMENTS_DATABASE_TOO_LARGE',
  READER_CONNECTION_NOT_AVAILABLE_OFFLINE:
    'READER_CONNECTION_NOT_AVAILABLE_OFFLINE',
  LOCATION_CONNECTION_NOT_AVAILABLE_OFFLINE:
    'LOCATION_CONNECTION_NOT_AVAILABLE_OFFLINE',
  NO_LAST_SEEN_ACCOUNT: 'NO_LAST_SEEN_ACCOUNT',
  INVALID_OFFLINE_CURRENCY: 'INVALID_OFFLINE_CURRENCY',
  CARD_SWIPE_NOT_AVAILABLE: 'CARD_SWIPE_NOT_AVAILABLE',
  INTERAC_NOT_SUPPORTED_OFFLINE: 'INTERAC_NOT_SUPPORTED_OFFLINE',
  ONLINE_PIN_NOT_SUPPORTED_OFFLINE: 'ONLINE_PIN_NOT_SUPPORTED_OFFLINE',
  MOBILE_WALLET_NOT_SUPPORTED_ON_SETUP_INTENTS:
    'MOBILE_WALLET_NOT_SUPPORTED_ON_SETUP_INTENTS',
  OFFLINE_AND_CARD_EXPIRED: 'OFFLINE_AND_CARD_EXPIRED',
  OFFLINE_TRANSACTION_DECLINED: 'OFFLINE_TRANSACTION_DECLINED',
  OFFLINE_COLLECT_AND_CONFIRM_MISMATCH: 'OFFLINE_COLLECT_AND_CONFIRM_MISMATCH',
  OFFLINE_TESTMODE_PAYMENT_IN_LIVEMODE: 'OFFLINE_TESTMODE_PAYMENT_IN_LIVEMODE',
  OFFLINE_LIVEMODE_PAYMENT_IN_TESTMODE: 'OFFLINE_LIVEMODE_PAYMENT_IN_TESTMODE',
  OFFLINE_PAYMENT_INTENT_NOT_FOUND: 'OFFLINE_PAYMENT_INTENT_NOT_FOUND',
  MISSING_EMV_DATA: 'MISSING_EMV_DATA',
  CONNECTION_TOKEN_PROVIDER_ERROR_WHILE_FORWARDING:
    'CONNECTION_TOKEN_PROVIDER_ERROR_WHILE_FORWARDING',
  ACCOUNT_ID_MISMATCH_WHILE_FORWARDING: 'ACCOUNT_ID_MISMATCH_WHILE_FORWARDING',
  FORCE_OFFLINE_WITH_FEATURE_DISABLED: 'FORCE_OFFLINE_WITH_FEATURE_DISABLED',
  NOT_CONNECTED_TO_INTERNET_AND_REQUIRE_ONLINE_SET:
    'NOT_CONNECTED_TO_INTERNET_AND_REQUIRE_ONLINE_SET',
  TEST_CARD_IN_LIVEMODE: 'TEST_CARD_IN_LIVEMODE',

  // Collect Inputs
  COLLECT_INPUTS_APPLICATION_ERROR: 'COLLECT_INPUTS_APPLICATION_ERROR',
  COLLECT_INPUTS_TIMED_OUT: 'COLLECT_INPUTS_TIMED_OUT',
  COLLECT_INPUTS_INVALID_PARAMETER: 'COLLECT_INPUTS_INVALID_PARAMETER',
  COLLECT_INPUTS_UNSUPPORTED: 'COLLECT_INPUTS_UNSUPPORTED',

  // Reader settings / security / surcharge
  READER_SETTINGS_ERROR: 'READER_SETTINGS_ERROR',
  READER_MISSING_ENCRYPTION_KEYS: 'READER_MISSING_ENCRYPTION_KEYS',
  OFFLINE_ENCRYPTION_KEYS_UNAVAILABLE: 'OFFLINE_ENCRYPTION_KEYS_UNAVAILABLE',
  INVALID_SURCHARGE_PARAMETER: 'INVALID_SURCHARGE_PARAMETER',
  READER_COMMUNICATION_SSL_ERROR: 'READER_COMMUNICATION_SSL_ERROR',
  ALLOW_REDISPLAY_INVALID: 'ALLOW_REDISPLAY_INVALID',
  CANCELED_DUE_TO_INTEGRATION_ERROR: 'CANCELED_DUE_TO_INTEGRATION_ERROR',

  // Printer
  PRINTER_BUSY: 'PRINTER_BUSY',
  PRINTER_PAPERJAM: 'PRINTER_PAPERJAM',
  PRINTER_OUT_OF_PAPER: 'PRINTER_OUT_OF_PAPER',
  PRINTER_COVER_OPEN: 'PRINTER_COVER_OPEN',
  PRINTER_ABSENT: 'PRINTER_ABSENT',
  PRINTER_UNAVAILABLE: 'PRINTER_UNAVAILABLE',
  PRINTER_ERROR: 'PRINTER_ERROR',
} as const;

// value union of ErrorCode
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
