source 'https://rubygems.org'
# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '3.2.2'
gem 'cocoapods', '~> 1.11', '>= 1.12.1'
gem 'activesupport', '~> 7.0', '<= 7.0.8'
